# https://github.com/44smkn/md-to-pdf-sample
name: Generate CV PDF

on:
  push:
    branches:
      - master

jobs:
  convert_via_pandoc:
    needs: push_image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          make setup
          make test
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: work/pdf/01_Doc.pdf work/pdf/01_Doc_en.pdf
