# https://github.com/44smkn/md-to-pdf-sample
name: Generate CV PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output
      - uses: docker://ghcr.io/44smkn/pandoc/ja:0.1.1
        with:
          args: markdown/01_Doc.md -s -o 01_Doc.pdf -c markdown-pdf.css --pdf-engine=wkhtmltopdf
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: 01_Doc.pdf
