name: push_image

on:
  push:
    branches:
      - master

jobs:
  push_image:
    env:
      IMAGE_NAME: printout
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.BUILD_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
  convert_via_pandoc:
    needs: push_image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          make setup
          make test
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: work/pdf/01_Doc.pdf work/pdf/01_Doc_en.pdf
