name: push_image

on:
  push:
    branches:
      - master

jobs:
  push:
    env:
      CTN: i13302/printout
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v1
        - name: build & push Docker Image
          run: |
            echo ${{ secrets.GHCR }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            make build
            docker tag ${{ env.CTN }} ghcr.io/${{ github.repository }}/${{ env.CTN }}:latest
            docker push ghcr.io/${{ github.repository }}/${{ env.CTN }}:latest
