name: push_image

on:
  push:
    branches:
      - master

jobs:
  push_image:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: ["pandoc", "printout"]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: create tag
        run: |
          SHA=${{ github.sha }}
          TAG=$(TZ=UTC-9 date '+%Y%m')-${SHA:0:7}
          echo "TAGS=$TAG" >> $GITHUB_ENV
          echo TAG $TAG

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.BUILD_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.target }}:${{ env.TAGS }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.target }}:latest

  convert_file:
    needs: push_image
    runs-on: ubuntu-20.04
    steps:
      - name: chackout
        uses: actions/checkout@v2

      - name: Convert file markdown to pdf
        run: |
          make setup
          make CTN2=ghcr.io/i13302/printout test_file

      - name: Upload file pdf.
        uses: actions/upload-artifact@master
        with:
          name: convert_file
          path: test/pdf/*.pdf

  convert_dir:
    needs: push_image
    runs-on: ubuntu-20.04
    steps:
      - name: chackout
        uses: actions/checkout@v2

      - name: Convert file markdown to pdf
        run: |
          make setup
          make CTN2=ghcr.io/i13302/printout test_run

      - name: Upload file pdf.
        uses: actions/upload-artifact@master
        with:
          name: convert_dir
          path: test/pdf/*.pdf
