name: push_image

on:
  push:
    branches:
      - master

jobs:
  env:
      CTN: i13302/printout
  build:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v1
        - name: build Dockerfile
          run:
            make build
  push:
    runs-on: ubuntu-20.04
      needs: build
      steps:
        - name: push Image to Pacakge
          run: |
            echo ${{ secrets.GHCR }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker build . -t ${{ env.CTN }}
            docker tag ${{ env.CTN }} ghcr.io/${{ github.repository }}/${{ env.CTN }}:latest
            docker push ghcr.io/${{ github.repository }}/${{ env.CTN }}:latest
